investment_sites:
  briq:
    user: oswaldocs94@gmail.com
    password: /proyectos
  cumplo:
    user: oswaldocs94@gmail.com
    password: /
  m2crowd:
    user: oswaldocs94@gmail.com
    password: /offerings/browse
