investment_sites:
  briq:
    url: https://www.briq.mx
    home: /proyectos
    login:
      url: /users/sign_in
      user: //*[@id="user_email"]
      password: //*[@id="user_password"]
      button: //*[@id="new_user"]/div[4]/div/input
    projects:
      filter:
        tag:
          img: src
          regex: abel_buscando-inversion
      map:
        parent: href
  cumplo:
    url: https://www.cumplo.mx
    home: /
  m2crowd:
    url: https://www.m2crowd.com
    home: /offerings/browse
driver:
  path: ./chromedriver
