investment_sites:
  briq:
    url: https://www.briq.mx
    home: /proyectos
  cumplo:
    url: https://www.cumplo.mx
    home: /
  m2crowd:
    url: https://www.m2crowd.com
    home: /offerings/browse
  
