investment_sites:
  briq:
    url: https://www.briq.mx
    current_projetcs:
      url: /proyectos
    login:
      url: /users/sign_in
      user: //*[@id="user_email"]
      password: //*[@id="user_password"]
      button: //*[@id="new_user"]/div[4]/div/input
    projects:
      filter:
        tag:
          img: src
          regex: abel_buscando-inversion
      map:
        parent: href
  cumplo:
    url: https://www.cumplo.mx
    current_projetcs:
      url: /
      wait: //*[@id="app"]/div/main/div[2]/div/div/div[1]/div/a
    login:
      auth0: /html/body/main/div[1]/div/div/p/button
      url: /login
      user: //*[@id="auth0-lock-container-1"]/div/div[2]/form/div/div/div[3]/span/div/div/div/div/div/div/div/div/div[4]/div[1]/div/input
      password: //*[@id="auth0-lock-container-1"]/div/div[2]/form/div/div/div[3]/span/div/div/div/div/div/div/div/div/div[4]/div[2]/div/div/input
      button: /html/body/div/div/div[2]/form/div/div/button
  m2crowd:
    url: https://www.m2crowd.com
    home: /offerings/browse
driver:
  path: ./chromedriver
